server:
  port: 8081
---
spring:
  profiles: test
  application:
    name: herokuautodeploy-test
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: dev
  application:
    name: herokuautodeploy-dev
management:
  endpoints:
    web:
      exposure:
        include: "info,health,trace,env"
---
spring:
  profiles: staging
  application:
    name: herokuautodeploy-staging
management:
  endpoints:
    web:
      exposure:
        include: "info,env,health"
---
spring:
  profiles: prod
  application:
    name: herokuautodeploy-prod
management:
  endpoints:
    web:
      exposure:
        include: "info,env,health"