# This workflow will build and deploy artifact to Heroku whenever Merge to Main branch
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Deploy to Heroku Work Flow

on:
  push:
    branches: [ main,dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku Prod/Test Region
        if: github.ref == 'refs/heads/main'  # This will make this workflow take main branch code to deploy
        uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "herokuautodeploy-test"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          remote_branch: main # This is optional in case different branch use that here.
          usedocker: true

      - name: Deploy to Heroku Dev Region
        if: github.ref == 'refs/heads/dev'  # This will make this workflow take dev branch code to deploy
        uses: akhileshns/heroku-deploy@v3.10.9
        with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "herokuautodeploy-dev"
            heroku_email: ${{secrets.HEROKU_EMAIL}}
            remote_branch: main # This is optional in case different branch use that here.
            usedocker: true

